# Generated by Django 4.2.7 on 2024-01-06 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_taskgroup_alter_task_owner_task_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
